In [1]:
import actonet
import biolqm
from colomoto.minibn import BooleanNetwork
from colomoto_jupyter import tabulate
import cabean # for attractor computation

This notebook has been executed using the docker image `colomoto/colomoto-docker:2020-07-01`

In this notebook we compare the results obtained with actonet, stable motifs and caspo-control on the tumor invasion model

Definition of targets

In [2]:
targets = {"CellCycleArrest": 1,"EMT":1,"Invasion":1,"Migration":1,"Metastasis":1,"Apoptosis":0}

Computation of wild-type model attractors

In [3]:
model = biolqm.load("http://ginsim.org/sites/default/files/SuppMat_Model_Master_Model.zginml")
test = biolqm.to_minibn(model, ensure_boolean=True)
att=cabean.attractors(test)
tabulate(att)

Downloading http://ginsim.org/sites/default/files/SuppMat_Model_Master_Model.zginml

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1
2,0,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0
3,0,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,1
4,0,0,1,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,1,1,0,0
5,0,1,0,0,1,0,1,0,0,0,1,1,1,0,0,0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0
6,0,1,0,0,1,0,1,0,1,0,1,1,1,0,0,0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0
7,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
8,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

# without sources

## caspo-control solutions
The solution set computed by caspo-control for the target previously defined with no sources is an={(NICD=1, SNAI2=1),(AKT2=1, ECMicroenv=1),(NICD=1, SNAI2=1),(AKT2=1, NICD=1)}

In [4]:
nos_cc1 = biolqm.to_minibn(model, ensure_boolean=True)
nos_cc1["AKT2"] = 1
nos_cc1["ECMicroenv"] = 1
nos_att1=cabean.attractors(nos_cc1)
tabulate(nos_att1)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

Both stable states are attractors of of the wild-type model :

In [5]:
nos_att1_t=[[a==b for a in list(att)] for b in list(nos_att1)]
nos_att1_t

[[False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, True]]

In [6]:
nos_cc2 = biolqm.to_minibn(model, ensure_boolean=True)
nos_cc2["AKT2"] = 1
nos_cc2["NICD"] = 1
nos_att2=cabean.attractors(nos_cc2)
tabulate(nos_att2)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [7]:
nos_att2_t=[[a==b for a in list(att)] for b in list(nos_att2)]
nos_att2_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, True]]

In [8]:
nos_cc3 = biolqm.to_minibn(model, ensure_boolean=True)
nos_cc3["SNAI2"] = 1
nos_cc3["NICD"] = 1
nos_att3=cabean.attractors(nos_cc3)
tabulate(nos_att3)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [9]:
nos_att3_t=[[a==b for a in list(att)] for b in list(nos_att3)]
nos_att3_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, True]]

## actonet solutions
The solution set computed by actonet for the target previously defined with no sources is 
an={(NICD=1, p53=0),(NICD=1, p73=1),(DNAdamage=0, ECMicroenv=1),(NICD=1, SNAI2=1),(AKT2=1, ECMicroenv=1),(AKT2=1, NICD=1)(AKT2=1, SNAI1=0),(AKT2=1, TGFbeta=1),(AKT2=1, Invasion=1),(AKT2=1, SMAD=1)}

In [10]:
nos_an4 = biolqm.to_minibn(model, ensure_boolean=True)
nos_an4["p53"] = 0
nos_an4["NICD"] = 1
nos_att4=cabean.attractors(nos_an4)
tabulate(nos_att4)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [11]:
nos_att4_t=[[a==b for a in list(att)] for b in list(nos_att4)]
nos_att4_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, True]]

In [12]:
nos_an5 = biolqm.to_minibn(model, ensure_boolean=True)
nos_an5["p73"] = 1
nos_an5["NICD"] = 1
nos_att5=cabean.attractors(nos_an5)
tabulate(nos_att5)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1
1,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1
2,0,1,0,0,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1

In [13]:
nos_att5_t=[[a==b for a in list(att)] for b in list(nos_att5)]
nos_att5_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, False]]

In [14]:
nos_an6 = biolqm.to_minibn(model, ensure_boolean=True)
nos_an6["DNAdamage"] = 0
nos_an6["ECMicroenv"] = 1
nos_att6=cabean.attractors(nos_an6)
tabulate(nos_att6)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [15]:
nos_att6_t=[[a==b for a in list(att)] for b in list(nos_att6)]
nos_att6_t

[[False, False, False, False, False, False, False, True, False]]

In [16]:
nos_an7=biolqm.to_minibn(model, ensure_boolean=True)
nos_an7["AKT2"] = 1
nos_an7["SNAI1"] = 0

In [17]:
nos_att7=cabean.attractors(nos_an7)
tabulate([nos_att7[0]])

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0

In [18]:
nos_att7_t0=[a==nos_att7[0] for a in list(att)]
nos_att7_t0

[False, False, False, False, False, False, False, False, False]

In [19]:
tabulate([nos_att7[1]])

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0

In [20]:
nos_att7_t1=[a==nos_att7[1] for a in list(att)]
nos_att7_t1

[False, False, False, False, False, False, False, False, False]

In [21]:
tabulate(nos_att7[2])

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
1,*,1,0,0,0,1,*,*,0,0,*,*,1,*,*,*,0,0,0,*,0,*,*,*,*,0,0,0,*,0,0,0
2,*,1,0,0,1,1,*,*,0,0,*,*,1,*,*,*,0,0,0,*,0,1,*,*,*,0,0,0,*,0,0,0
0,*,1,0,0,*,0,*,*,0,0,*,*,1,*,*,*,0,0,0,*,0,*,*,*,*,0,0,0,*,0,0,0

In [22]:
tabulate(nos_att7[3])

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
1,*,1,0,0,0,1,*,*,1,0,*,*,1,*,*,*,0,0,0,*,0,*,*,*,*,0,0,0,*,0,0,0
2,*,1,0,0,1,1,*,*,1,0,*,*,1,*,*,*,0,0,0,*,0,1,*,*,*,0,0,0,*,0,0,0
0,*,1,0,0,*,0,*,*,1,0,*,*,1,*,*,*,0,0,0,*,0,*,*,*,*,0,0,0,*,0,0,0

In [23]:
nos_an8 = biolqm.to_minibn(model, ensure_boolean=True)
nos_an8["AKT2"] = 1
nos_an8["TGFbeta"] = 1
nos_att8=cabean.attractors(nos_an8)
tabulate(nos_att8)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,0,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [24]:
nos_att8_t=[[a==b for a in list(att)] for b in list(nos_att8)]
nos_att8_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, True]]

In [25]:
nos_an9 = biolqm.to_minibn(model, ensure_boolean=True)
nos_an9["AKT2"] = 1
nos_an9["Invasion"] = 1
nos_att9=cabean.attractors(nos_an9)
tabulate(nos_att9)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,0,1,0,1,1,1,1,1,1,0,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [26]:
nos_att9_t=[[a==b for a in list(att)] for b in list(nos_att9)]
nos_att9_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, True]]

In [27]:
nos_an10 = biolqm.to_minibn(model, ensure_boolean=True)
nos_an10["AKT2"] = 1
nos_an10["SMAD"] = 1
nos_att10=cabean.attractors(nos_an10)
tabulate(nos_att10)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,0,0,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0
1,0,1,0,0,1,0,1,0,1,0,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0
2,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0
3,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [28]:
nos_att10_t=[[a==b for a in list(att)] for b in list(nos_att10)]
nos_att10_t

[[False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, False, False],
 [False, False, False, False, False, False, False, True, False],
 [False, False, False, False, False, False, False, False, True]]

# with sources

In [29]:
sources = {"ECMicroenv":1,"DNAdamage":0}

## actonet solution
The solution set computed by actonet for the source,target couple defined previsouly is : an={}
The model with the sources fixed has a single stable state which verifies the desired values for the targets :

In [30]:
test1 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test1[n] = v
att1=cabean.attractors(test1)
tabulate(att1)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

This unique stable state is a stable state of the wild-type model :

In [31]:
t=[a==list(att1)[0] for a in list(att)]
t

[False, False, False, False, False, False, False, True, False]

## stable motifs solutions
The solution set computed by stable motifs for the source,target couple defined previsouly is :sm={(SNAI2=1),(p53=0)}
The model with the sources and solution fixed has a single stable state which verifies the desired values for the targets :

In [32]:
test2 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test2[n] = v
    test2["SNAI2"] = 1
att2=cabean.attractors(test2)
tabulate(att2)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

This unique stable state is a stable state of the wild-type model :

In [33]:
t=[a==list(att2)[0] for a in list(att)]
t

[False, False, False, False, False, False, False, True, False]

In [34]:
test3 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test3[n] = v
    test3["p53"] = 0
att3=cabean.attractors(test3)
tabulate(att3)

,AKT1,AKT2,Apoptosis,CDH1,CDH2,CTNNB1,CellCycleArrest,DKK1,DNAdamage,ECMicroenv,EMT,ERK,GF,Invasion,Metastasis,Migration,NICD,SMAD,SNAI1,SNAI2,TGFbeta,TWIST1,VIM,ZEB1,ZEB2,miR200,miR203,miR34,p21,p53,p63,p73
0,0,1,0,0,1,0,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0

In [35]:
t=[a==list(att3)[0] for a in list(att)]
t

[False, False, False, False, False, False, False, True, False]

## caspo solutions
The solution set computed by caspo-control for the source,target couple defined previsouly is :
cc={(p53=0),(AKT2=1),(SNAI2=1),(NICD=0, SNAI1=1),(Migration=1, SNAI1=1),(SNAI1=1, p73=1)}²

In [36]:
test_cc3 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test_cc3[n] = v
    test_cc3["AKT2"] = 1
att_cc3=cabean.attractors(test_cc3)
tabulate(att_cc3)

t_cc3=[a==list(att_cc3)[0] for a in list(att)]
t_cc3

[False, False, False, False, False, False, False, True, False]

In [37]:
test_cc4 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test_cc4[n] = v
    test_cc4["NICD"] = 0
    test_cc4["SNAI1"] = 1
att_cc4=cabean.attractors(test_cc4)
tabulate(att_cc4)

t_cc4=[a==list(att_cc4)[0] for a in list(att)]
t_cc4

[False, False, False, False, False, False, False, False, False]

In [38]:

test_cc5 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test_cc5[n] = v
    test_cc5["Migration"] = 1
    test_cc5["SNAI1"] = 1
att_cc5=cabean.attractors(test_cc5)
tabulate(att_cc5)

t_cc5=[a==list(att_cc5)[0] for a in list(att)]
t_cc5

[False, False, False, False, False, False, False, True, False]

In [39]:
test_cc6 = biolqm.to_minibn(model, ensure_boolean=True)
for n, v in sources.items():
    test_cc6[n] = v
    test_cc6["p73"] = 1
    test_cc6["SNAI1"] = 1
att_cc6=cabean.attractors(test_cc6)
tabulate(att_cc6)

t_cc6=[a==list(att_cc6)[0] for a in list(att)]
t_cc6

[False, False, False, False, False, False, False, False, False]